snakeeyes/blueprints/user/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError, Optional
from wtforms_components import EmailField, Email
from snakeeyes.blueprints.user.models import User


class LoginForm(Form):
    email = StringField('Email', validators=[DataRequired(), Length(min=5, max=35, message="Your password must be 8-32 character long")])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8, max=32)])
    remember_me = BooleanField('Keep me signed in.')


class RegisterForm(Form):
    email = EmailField('Email', validators=[DataRequired(), Email(), Length(min=5, max=35)])
    password = PasswordField('Password', validators=[DataRequired(), 
                                            Length(min=8, max=32, message="Your password must be 8-32 character long")])
    confirm_password = PasswordField("Confirm password", validators=[DataRequired(), 
                        Length(min=8, max=32, message="Your password must be 8-32 character long"), EqualTo('password', message='Your input must match the password field.')])

    def validate_email(self, email):
        user= User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("Email already taken")


class WelcomeForm(Form):
    username = StringField("Username", validators=[DataRequired(), Length(min=4, max=24, message='Username must be 4-24 character long')])

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("Username already taken by another user, please choose another username. Thanks")


class RequestPasswordResetForm(Form):
    email = EmailField("Email", validators=[DataRequired(), Email(), Length(min=5, max=35)])

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError("There's no user with these email, sign up to create an account.")


class NewPasswordForm(Form):
    password = PasswordField('Enter a new password', validators=[DataRequired(), Length(min=8, max=32, message="Your password must be 8-32 character long")])
    confirm_password = PasswordField('Confirm password', validators=[DataRequired(), Length(min=8, max=32), EqualTo('password', message='Your input must match the password field.')])


class UpdateAccountForm(Form):
    email = EmailField("Email", validators=[DataRequired(), Email(), Length(min=5, max=35)])
    password = PasswordField('Password', validators=[Optional(), 
                                            Length(min=8, max=32, message="Your password must be 8-32 character long")])
    confirm_password = PasswordField("Confirm password", validators=[Optional(), 
                                            Length(min=8, max=32, message="Your password must be 8-32 character long"), EqualTo(password, message='Your input must match the password field.')])

    def validate_username(self, email):
        user = User.query.filter_by(username=email.data).first()
        if user:
            raise ValidationError("Email already taken by another user, please choose another username. Thanks")


class PasswordForm(Form):
    email = EmailField("Email", validators=[DataRequired(), Email(), Length(min=5, max=35)])
            

snakeeyes/blueprints/billing/views/billing.py
from flask import Blueprint, request, redirect, url_for, render_template, flash, current_app, render_template
from flask_login import current_user, login_required
from config import settings
from snakeeyes.blueprints.billing.decorators import subscription_required, handle_stripe_exceptions
from snakeeyes.blueprints.billing.models.subscriptions import Subscription
from snakeeyes.blueprints.billing.models.invoice import Invoice 
from snakeeyes.blueprints.billing.models.coupon import Coupon
from snakeeyes.blueprints.billing.forms import CreditCardForm, UpdateSubscriptionForm, CancelSubscriptionForm
from config import settings

billing = Blueprint('billing', __name__, template_folder='../templates', url_prefix='/billing')


@billing.route('/pricing')
def pricing():
    if current_user.is_authenticated and current_user.subscription:
        return redirect(url_for('billing.update'))

    form = UpdateSubscriptionForm()

    return render_template('billing/pricing.html', form=form,
                           plans=settings.STRIPE_PLANS)


@billing.route('/create', methods=['GET', 'POST'])
@handle_stripe_exceptions
@login_required
def create():
    if current_user.subscription:
        flash('You already have an active subscription.', 'info')
        return redirect(url_for('user.settings'))

    plan = request.args.get('plan')
    subscription_plan = Subscription.get_plan_by_id(plan)

    # Guard against an invalid or missing plan.
    if subscription_plan is None and request.method == 'GET':
        flash('Sorry, that plan did not exist.', 'error')
        return redirect(url_for('billing.pricing'))

    stripe_key = current_app.config.get('STRIPE_PUBLISHABLE_KEY')
    print(stripe_key)
    form = CreditCardForm(stripe_key=stripe_key, plan=plan)
    
    if form.validate_on_submit():
        subscription = Subscription()
        created = subscription.create(user=current_user,
                                      name=request.form.get('name'),
                                      plan=request.form.get('plan'),
                                      coupon=request.form.get('coupon_code'),
                                      token=request.form.get('stripe_token'))
        print(request.form.get('stripe_token'))
        if created:
            flash('Awesome, thanks for subscribing!', 'success')
        else:
            flash('You must enable JavaScript for this request.', 'warning')

        return redirect(url_for('user.settings'))

    return render_template('billing/payment_method.html',
                           form=form, plan=subscription_plan)


@billing.route('/update', methods=['GET', 'POST'])
@handle_stripe_exceptions
@subscription_required 
@login_required
def update():
    current_plan = current_user.subscription.plan
    active_plan = Subscription.get_plan_by_id(current_plan)
    new_plan = Subscription.get_new_plan(request.form.keys())

    plan = Subscription.get_plan_by_id(new_plan)

    # Guard against an invalid, missing or identical plan.
    is_same_plan = new_plan == active_plan['id']
    if ((new_plan is not None and plan is None) or is_same_plan) and \
            request.method == 'POST':
        return redirect(url_for('billing.update'))

    form = UpdateSubscriptionForm(coupon_code=current_user.subscription.coupon)

    if form.validate_on_submit():
        subscription = Subscription()
        updated = subscription.update(user=current_user,
                                      coupon=request.form.get('coupon_code'),
                                      plan=plan.get('id'))

        if updated:
            flash('Your subscription has been updated.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('billing/pricing.html',
                           form=form,
                           plans=settings.STRIPE_PLANS,
                           active_plan=active_plan)


@billing.route('/cancel', methods=['GET', 'POST'])
@handle_stripe_exceptions
@login_required
def cancel():
    if not current_user.subscription:
        flash('You do not have an active subscription.', 'error')
        return redirect(url_for('user.settings'))

    form = CancelSubscriptionForm()

    if form.validate_on_submit():
        subscription = Subscription()
        cancelled = subscription.cancel(user=current_user)

        if cancelled:
            flash('Sorry to see you go, your subscription has been cancelled.',
                  'success')
            return redirect(url_for('user.settings'))

    return render_template('billing/cancel.html', form=form)


@billing.route('/update_payment_method', methods=['GET', 'POST'])
@handle_stripe_exceptions
@login_required
def update_payment_method():
    if not current_user.credit_card:
        flash('You do not have a payment method on file.', 'error')
        return redirect(url_for('user.settings'))

    active_plan = Subscription.get_plan_by_id(
        current_user.subscription.plan)

    card = current_user.credit_card
    stripe_key = current_app.config.get('STRIPE_PUBLISHABLE_KEY')
    form = CreditCardForm(stripe_key=stripe_key,
                          plan=active_plan,
                          name=current_user.name)

    if form.validate_on_submit():
        subscription = Subscription()
        updated = subscription.update_payment_method(user=current_user,
                                                     credit_card=card,
                                                     name=request.form.get(
                                                         'name'),
                                                     token=request.form.get(
                                                         'stripe_token'))
        print(request.form.get('stripe_token'))

        if updated:
            flash('Your payment method has been updated.', 'success')
        else:
            flash('You must enable JavaScript for this request.', 'warning')

        return redirect(url_for('user.settings'))

    return render_template('billing/payment_method.html', form=form,
                           plan=active_plan, card_last4=str(card.last4))

@billing.route('/billing_details')
@handle_stripe_exceptions
@login_required
def billing_details():
    invoices = Invoice.billing_history(current_user)

    if current_user.subscription:
        upcoming = Invoice.upcoming(current_user.payment_id)
        coupon = Coupon.query.filter(Coupon.code == current_user.subscription.coupon).first()

    else:
        upcoming = None
        coupon = None

    return render_template('billing/billing_details.html', upcoming = upcoming, invoices=invoices, coupon=coupon)

snakeeyes/blueprints/user/__init__.py
from flask import Blueprint


user = Blueprint('user', __name__, template_folder='templates')


from snakeeyes.blueprints.user import views

snakeeyes/blueprints/user/views.py
from flask import flash, request, url_for, render_template, redirect, current_app
from snakeeyes.blueprints.user.forms import LoginForm, RegisterForm, WelcomeForm, RequestPasswordResetForm, NewPasswordForm, UpdateAccountForm, PasswordField
from snakeeyes.blueprints.user import user
from flask_login import login_user, logout_user, login_required, current_user, confirm_login
from snakeeyes.blueprints.user.user_utils import safe_url
from snakeeyes.blueprints.user.models import User
from snakeeyes.email import send_mail
from snakeeyes.extensions import db


@user.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_token()
        send_mail(user.email, 'contact', 'user/mail/index', customer=user ,token=token )
        flash('Your account has been created, you can now login with your email and password', 'success')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form = form )


@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash("Operation already performed", 'info')
        return redirect(url_for('page.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        current_app.logger.debug('{0} has tried to log in with ip : {1}'.format(form.email.data, request.remote_addr))

        if user is not None and user.verify_password(form.password.data):
            if login_user(user, remember=True) and user.is_active():
                flash('Log in successful', 'success')
                user.track_user_activities(request.remote_addr)
                next_page = request.args.get('next')
                if next_page:
                    return redirect(safe_url(next_page))
                else:
                    return redirect(url_for('page.home'))
            else:
                flash("Your account has been temporary disable, please visit support for assisstance", 'info')
                return redirect(url_for('user.login'))
        elif user is None:
            flash("You need to register in order to access this page", 'info')
        else:
            flash('Incorrect password or email.', 'danger')
    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You are logged out", 'success')
    return redirect(url_for('user.login'))


@user.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('page.home'))
    if current_user.verify_token(token):
        flash("Your account has been verified", 'success')
    else:
        flash('The confirmation link has expired or invalid', 'danger')
    return redirect(url_for('page.home'))


@user.before_app_request
def before_request():
    if current_user.is_authenticated and not current_user.confirmed and request.endpoint[:5] != 'user.':
        return redirect(url_for('user.unconfirmed'))


@user.route('/unconfirmed')
def unconfirmed():
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('page.home'))
    return render_template('user/unconfirmed.html')


@user.route('/resend_link')
@login_required
def resend_link():
    token = current_user.generate_token()
    send_mail(current_user.email, 'contact', 'user/mail/unconfirmed', user = current_user, token=token )
    flash("A new new email with a confirmation has been sent to your email.", 'success')
    return redirect(url_for('page.home'))


@user.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        return redirect(url_for('user.settings'))
    form = WelcomeForm()
    if form.validate_on_submit():
        current_user.username = form.username.data 
        db.session.commit()
        flash("Sign up is complete, you can now enjoy our serveices. Thank you.")
        return redirect(url_for('user.settings'))
    return render_template('user/welcome.html', form=form)


@user.route('/updateaccount', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        new_password = form.password.data
        new_email = form.email.data
        if new_password:
            current_user.password = new_password
            flash('Your password has been updated', 'success')
        elif new_email:
            current_user.email = new_email
            db.session.commit()
            flash('Your email has been updated', 'success')
            send_mail(current_user.email, 'contact', 'user/mail/index', token=token )
        else:
            flash("Your credentials has been updated", 'Thanks')
    return render_template('user/updatecredentials.html', form = form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/requestpasswordreset', methods=['GET', 'POST'])
def requestpasswordreset():
    if current_user.is_authenticated:
        flash("Operation already performed", 'info')
        return redirect(url_for('page.home'))
    form = RequestPasswordResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user:
            token = user.generate_reset_token()
            send_mail(user.email, 'reset password token', 'user/mail/reset_password', user = user, token=token )
            flash('Password reset link had been sent to your email', 'success')
            return redirect(url_for('user.login'))
        else:
            flash('Unable to find your account', 'warning')
            return redirect(url_for('user.requestpasswordreset'))
    return render_template('user/requestpasswordreset.html', form = form)


@user.route('/new_password/<token>', methods=['GET', 'POST'])
def newpassword(token):
    if current_user.is_authenticated:
        flash("Operation already performed", 'info')
        return redirect(url_for('page.home'))
      
    form = NewPasswordForm()
    if form.validate_on_submit():
        user = User.confirm_reset_token(token)
        if user is None:
            flash('Your reset token has expired or invalid', 'danger')
            return redirect(url_for('user.requestpasswordreset'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your password has been reset successfully.', 'success')
        return redirect(url_for('user.login'))
    return render_template('user/newpassword.html', form=form)



    


    
    




















    
    

snakeeyes/blueprints/user/templates/user/login.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Sign in to access your account{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.login') %}
         {{ form.hidden_tag() }}
        <legend>Sign in to continue</legend>

        {% call f.form_group(form.email, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        
      <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Sign in
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.register') }}"
               class="btn btn-default btn-block">
              Register
            </a>
          </div>
        </div>
      {% endcall %}

      <div class="text-center md-margin-top">
        <a href="{{url_for('user.requestpasswordreset')}}" class="text-muted">
          Forgot your password?
        </a>
      </div>
    </div>
  </div>
{% endblock %}

snakeeyes/blueprints/user/templates/user/newpassword.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}


{% block title %}Enter a new password{% endblock %}


{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.newpassword', token='token') %}
        <legend>Enter a new password</legend>

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        {% call f.form_group(form.confirm_password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
               class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

snakeeyes/blueprints/user/templates/user/register.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %} Sign up for new account  {% endblock %}

{% block header %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{{ url_for('page.home') }}">
          <img src="{{ url_for('static', filename='images/snake-eyes.jpg') }}"
               class="img-responsive"
               width="229" height="50" title="Snake Eyes" alt="Snake Eyes"/>
        </a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="{{ url_for('user.settings') }}" class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button" aria-haspopup="true"
                 aria-expanded="false">Account
                <span class="caret"></span></a>
                <li><a href="{{url_for('user.logout')}}">logout</a></li>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('user.settings') }}">Settings</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session</li>
                <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
              </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}">Log in</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
        <h2>What are you waiting for?</h2>

        <div class="media md-margin-bottom">
            <div class="media-left">
            <i class="fa fa-fw fa-3x fa-bullhorn text-primary"></i>
            </div>
            <div class="media-body">
            <h4 class="media-heading">Place bets</h4>
            <span class="text-muted">
                Correctly guess the dice's roll.
            </span>
            </div>
        </div>
        <div class="media md-margin-bottom">
            <div class="media-left">
            <i class="fa fa-fw fa-3x fa-database text-primary"></i>
            </div>
            <div class="media-body">
            <h4 class="media-heading">Win currency</h4>
            <span class="text-muted">
                Gain coins if your guess is correct.
            </span>
            </div>
        </div>
        <div class="media md-margin-bottom">
            <div class="media-left">
            <i class="fa fa-fw fa-3x fa-trophy text-primary"></i>
            </div>
            <div class="media-body">
            <h4 class="media-heading">Leaderboard</h4>
            <span class="text-muted">Compare your results to others.</span>
            </div>
        </div>
        </div>
    <div class="col-md-5 col-md-push-1 col-md-offset-1 well">
    {% call f.form_tag('user.register') %}

       
        {% call f.form_group(form.email, css_class='sm-margin-bottom' , autofocus='autofocus', placeholder='Your email address')  %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='sm-margin-bottom', autofocus='autofocus', placeholder='Input your password')  %}
        {% endcall %}

        {% call f.form_group(form.confirm_password, css_class='sm-margin-bottom' , autofocus='autofocus', placeholder='Confirm your password')  %}
        {% endcall %}

        <div class="row">
            <div class="col-md-6">
              <button type="submit" class="btn btn-primary btn-block">
                Register
              </button>
            </div>
            <div class="col-md-6">
              <div class="visible-xs visible-sm sm-margin-top"></div>
              <a href="{{ url_for('user.login') }}"
                 class="btn btn-default btn-block">
                Looking to sign in?
              </a>
            </div>
        </div>     
    {% endcall %}
    </div>
    </div>
{% endblock %}

snakeeyes/blueprints/user/templates/user/requestpasswordreset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Reset your password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.requestpasswordreset') %}
        <legend>Reset your password</legend>
        <p class="small help-block sm-margin-bottom">
          We'll send you an email to reset your password.
        </p>

        {% call f.form_group(form.email, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
                class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

snakeeyes/blueprints/user/templates/user/settings.html
{% extends 'layouts/app.html' %}

{% block title %}Account settings{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">
      <h2>Settings</h2>
      <h4 class="text-muted margin-bottom">{{ current_user.email }}</h4>

      <div class="list-group">
        <a href="{{ url_for('user.update_credentials') }}"
           class="list-group-item">
          Update email and password
        </a>
        {% if current_user.username %}
          <span class="list-group-item quarter-faded text-muted">
            Your username is
            <strong>{{ current_user.username }}</strong>
          </span>
        {% else %}
          <a href="{{ url_for('user.welcome') }}"
             class="list-group-item">
            Pick a username
          </a>
        {% endif %}
      </div>
    </div>

    <div class="col-md-5 col-md-push-1 col-md-offset-1">
      {% if current_user.subscription %}
        <h2>{{ current_user.subscription.plan | title }}
          subscription</h2>
        <h4 class="text-muted margin-bottom">
          {{ current_user.credit_card.brand }}
          ****{{ current_user.credit_card.last4 }}
          ({{ current_user.credit_card.exp_date.strftime('%m/%Y') }})
        </h4>

        <div class="list-group">
          <a class="list-group-item"
             href="{{ url_for('billing.update_payment_method') }}">
            Update payment info
          </a>
          <a class="list-group-item"
             href="{{ url_for('billing.billing_details') }}">
            Billing details
          </a>
          <a class="list-group-item"
             href="{{ url_for('billing.update') }}">
            Change plan
          </a>
          <a class="list-group-item"
             href="{{ url_for('billing.cancel') }}">
            <span class="text-muted">Cancel subscription</span>
          </a>
        </div>
      {% else %}
        <h2>Subscribe today</h2>
        <h4 class="text-muted">
          Hey buddy, why aren't you subscribed?
        </h4>

        <p>
          Now that you've created an account, wouldn't it be unbelievably
          amazing to unlock everything by becoming a subscriber today?
        </p>
        <a href="{{ url_for('billing.pricing') }}"
           class="btn btn-primary">Learn more</a>

        <hr/>
        {% if current_user.invoices %}
          <h3>Previous subscription info</h3>
          <div class="list-group">
            <a class="list-group-item"
              href="{{ url_for('billing.billing_details') }}">
              Billing details
            </a>
          </div>
        {% endif %}
      {% endif %}
    </div>
  </div>
{% endblock %}

snakeeyes/blueprints/user/templates/user/unconfirmed.html
{% extends 'layouts/app.html' %}


{% block title %}Verify your account to access our services{% endblock %}

{% block body %}
    <h2> Hello, thank you for registering with us today. Your email address is : <strong>{{current_user.email}}</strong>, please do the folowing to activate your account and start enjoying our services. Thanks </h2>
    <ol>
        <p><li>Verify your email by click the link sent to your email address provided during your registration. </li></p>
        <br>
        <p>Thanks for your corperation. If you do not get a confirmation link, click on the below link to resend your activation link and it will be sent to your email address. </p>


       <strong><p>Need another confrimation email link</p></strong> <a href="{{url_for('user.resend_link')}}">Click here.</a>
    </ol>
{% endblock %}

snakeeyes/blueprints/user/templates/user/updatecredentials.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Update your sign in information{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.update_credentials') %}
        <legend>Update your sign in information</legend>
        <p class="small help-block sm-margin-bottom">
          Supply your current password to make any changes.
        </p>

        {% call f.form_group(form.current_password, css_class='lg-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.email, css_class='sm-margin-bottom') %}
        {% endcall %}
        {% call f.form_group(form.password, css_class='sm-margin-bottom',
                             placeholder='New password (optional)') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Save
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.settings') }}"
               class="btn btn-default btn-block">
              Nevermind
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}