snakeeyes/blueprints/admin/forms.py
from flask_wtf import Form
from wtforms import (
    StringField, 
    SelectField,
    ValidationError, 
    BooleanField, 
    SelectField, 
    IntegerField,
    FloatField, 
    DateTimeField
    )

from wtforms.validators import (
    DataRequired, 
    Optional, 
    Length,
    NumberRange
    )

from snakeeyes.blueprints.user.models import User
from lib.locale import Currency
from lib.utils_wtform import choices_from_dict
from snakeeyes.blueprints.billing.models.coupon import Coupon


class SearchForm(Form):
    search = StringField('Search terms', validators=[Optional(), Length(min=4, max=128)])


class BulkDeleteForm(Form):
    SCOPE = [
        ('all_selected_items', 'All selected items'),
        ('all_search_results', 'All search results')
    ]

    scope = SelectField('Priviledges', validators=[DataRequired()], choices= SCOPE)


class UserForm(Form):
    Role = [('member', "Member"),
        ("admin", "Admin")]

    coins = IntegerField('Coins', validators=[DataRequired(), 
                        NumberRange(min=1, max=21345678)])
    username = StringField('Username', validators=[Optional(), Length(min=4, max=28)])
    role = SelectField('Priviledegs', validators=[DataRequired()], choices = Role )
    active = BooleanField("Check to allow user to sign in.")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data ).first()

        if user :
            raise ValidationError("Username already taken by another user, please choose another username. Thanks")


class CanUserSubscriptionForm(Form):
    pass


class CouponForm(Form):
    percent_off = IntegerField('Percent of (%)',
                                validators=[Optional(), NumberRange(min=1, max=100)])
    amount_off = FloatField('Amount off ($)', 
                                validators=[Optional(), NumberRange(min=0.01, max=21474836.0)])
    
    code = StringField('Code', 
                            validators=[DataRequired(), Length(min=1, max=32)])
    
    currency = SelectField('Currency', validators=[DataRequired()], 
                            choices=choices_from_dict(Currency.TYPES, prepend_blank=False))
    
    duration = SelectField('Duaration', 
                            validators=[DataRequired()], 
                            choices=choices_from_dict(Coupon.DURATION, prepend_blank=False))
    
    duration_in_months = IntegerField('Duration', 
                        validators=[Optional(), NumberRange(min=1, max=12) ])
    
    max_redemptions = IntegerField('Max Redeemptions', 
                                    validators=[Optional(), NumberRange(min=1, max=2147483647)])
    
    redeem_by = DateTimeField('Redeem by', 
                                validators=[Optional()], format='%Y-%m-%d %H:%M:%S')

    def validate(self):
        if not Form.validate(self):
            return False

        result = True

        percent_off = self.percent_off.data
        amount_off = self.amount_off.data

        if percent_off is None and amount_off is None:
            empty_error = 'Pick atleast one.'
            self.percent_off.errors.append(empty_error)
            self.amount_off.errors.append(empty_error)
            result = False
        elif percent_off and amount_off:
            both_error = 'Cannot pick both'
            self.percent_off.errors.append(both_error)
            self.amount_off.errors.append(both_error)

            return False
        else:
            pass


        return result

snakeeyes/__init__.py
from flask import Flask
import logging
import stripe 

from logging.handlers import SMTPHandler

from werkzeug.middleware.proxy_fix import ProxyFix
from snakeeyes.blueprints.contact import contact
from snakeeyes.blueprints.page import page 
from snakeeyes.blueprints.user import user
from snakeeyes.blueprints.admin import admin 
from snakeeyes.blueprints.billing import billing
from snakeeyes.blueprints.billing import stripe_webhook
from snakeeyes.blueprints.error_page import error
from snakeeyes.blueprints.bet import bet
from snakeeyes.extensions import Csrf, mail, debug_toolbar, db, login_manager, limiter
from snakeeyes.blueprints.billing.template_processor import current_year, format_currency

login_manager.login_view = 'user.login'
login_manager.login_message = 'You need to login to access this page'
login_manager.login_message_category = 'info'
login_manager.session_protection = 'strong'
login_manager.refresh_view = 'user.login'
login_manager.needs_refresh_message = "To protect your account, please reauthenticate to access this page."
login_manager.needs_refresh_message_category = "info"

def create_app(override_settings=None):
    """
    Create a Flask application using the app factory pattern.

    :return: Flask app
    
    """
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object('config.settings')
    app.config.from_pyfile('settings.py', silent=True)

    if override_settings:
        app.config.update(override_settings)


    stripe.api_key = app.config.get('STRIPE_SECRET_KEY')
    stripe.api_version = app.config.get('STRIPE_API_VERSION')
    app.logger.setLevel(app.config['LOG_LEVEL'])

    middleware(app)
    exception_handler(app)
    app.register_blueprint(contact)
    app.register_blueprint(page)
    app.register_blueprint(user)
    app.register_blueprint(admin)
    app.register_blueprint(error)
    app.register_blueprint(billing)
    app.register_blueprint(bet)
    app.register_blueprint(stripe_webhook)
    template_processors(app)
    extension(app)

    return app


def extension(app):
    Csrf.init_app(app)
    mail.init_app(app)
    debug_toolbar.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    limiter.init_app(app)



def middleware(app):
    """This help to get the real ip address when using proxy server like nginx or load_balancer in production,
        it serve as a gateway between flask wsgi
    """

    app.wsgi_app = ProxyFix(app.wsgi_app)

    return None

def template_processors(app):
    """Registering our custom filter in jinja template"""
    app.jinja_env.filters['format_currency'] = format_currency

    app.jinja_env.globals.update(current_year=current_year)

    return app.jinja_env

def exception_handler(app):
    """
    Register 0 or more exception handlers (mutates the app passed in).

    :param app: Flask application instance
    :return: None
    """
    mail_handler = SMTPHandler((app.config.get('MAIL_SERVER'),
                                app.config.get('MAIL_PORT')),
                               app.config.get('MAIL_USERNAME'),
                               [app.config.get('MAIL_USERNAME')],
                               '[Exception handler] A 5xx was thrown',
                               (app.config.get('MAIL_USERNAME'),
                                app.config.get('MAIL_PASSWORD')),
                               secure=())

    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(logging.Formatter("""
    Time:               %(asctime)s
    Message type:       %(levelname)s


    Message:

    %(message)s
    """))
    app.logger.addHandler(mail_handler)

    return None

snakeeyes/blueprints/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, template_folder='templates', url_prefix='/admin')

from snakeeyes.blueprints.admin import views

snakeeyes/blueprints/admin/views.py
from flask import render_template, request, current_app, url_for, flash, redirect
from snakeeyes.blueprints.admin import admin
from flask_login import login_required
from snakeeyes.blueprints.admin.decorators import role_required
from snakeeyes.blueprints.admin.models import DashBoard
from snakeeyes.blueprints.admin.forms import SearchForm, UserForm, BulkDeleteForm , CanUserSubscriptionForm, CouponForm
from sqlalchemy import text
from snakeeyes.blueprints.user.models import User
from flask_login import current_user
from snakeeyes.extensions import db 
from snakeeyes.blueprints.billing.models.subscriptions import Subscription
from snakeeyes.blueprints.billing.decorators import handle_stripe_exceptions

from snakeeyes.blueprints.billing.models.coupon import Coupon


@admin.before_request
@login_required
@role_required('admin')
def before_request():
    """Function to monitor admin page"""
    pass


@admin.route('')
def dashboard():
    group_and_count_users = DashBoard.group_and_count_users()
    group_and_count_plans = DashBoard.group_and_count_plans()
    group_and_count_coupons = DashBoard.group_and_count_coupons()
    group_and_count_payouts = DashBoard.group_and_count_payouts()
    return render_template('admin/page/admin.html', group_and_count_users = group_and_count_users, 
                            group_and_count_coupons = group_and_count_coupons,
                            group_and_count_plans = group_and_count_plans, 
                            group_and_count_payouts=group_and_count_payouts)


@admin.route('/users')
def users():
    """Fucntion to list all users in the database."""
    form_search = SearchForm()
    bulk_form = BulkDeleteForm()
    sort_by = User.sort_by(request.args.get('sort', 'created_on'), 
                                            request.args.get('direction', 'desc'))
    order_values = '{0} {1}'.format(sort_by[0], sort_by[1])

    page = request.args.get('page', 1 , type=int)
    paginated_users = User.query \
        .filter(User.search(request.args.get('q', ''))) \
        .order_by(User.role.asc(), text(order_values)) \
        .paginate( page = page , per_page =current_app.config['FLASKY_POSTS_PER_PAGE'] , error_out = False )

    return render_template('admin/user/index.html', form=form_search,
                                users=paginated_users, bulk_form=bulk_form)


@admin.route('users/edit/<int:id>', methods=['GET', 'POST'])
def users_edit(id):
    user = User.query.get(id)
    form = UserForm()

    if form.validate_on_submit():
        if user.is_last_admin(user, form.role.data, form.active.data):
            flash("You are the last admin, you can't perform the operation.", 'error')
            return redirect(url_for('admin.users'))

        user.username = form.username.data
        user.active = form.active.data
        user.role = form.role.data
    
        if not user.username:
            user.username = None
        
        db.session.commit()

        if user.username:
            flash(f"{user.username} has been saved successfully", 'success')
            return redirect(url_for('admin.users'))
        else:
            flash('User has been saved successfully', 'success')
            return redirect(url_for('admin.users'))
    
    form.username.data = user.username
    form.active.data = user.active
    form.role.data = user.role
    db.session.commit()

    return render_template('admin/user/edit.html', form=form , user=user )


@admin.route('/users/bulk_delete', methods=['POST'])
def users_bulk_delete():
    form = BulkDeleteForm()

    if form.validate_on_submit():
        ids = User.get_bulk_action_id(request.form.get('scope'),
                                       request.form.getlist('bulk_ids'),
                                       omit_id=[current_user.id],
                                       query=request.args.get('q', ''))

        delete_count = User.bulk_delete(ids)

        flash('{0} user(s) were scheduled to be deleted.'.format(delete_count),
              'success')
    else:
        flash('No users were deleted, something went wrong.', 'error')

    return redirect(url_for('admin.users'))


@admin.route('/canel_user_subscription')
def canel_user_subscription():
    form = CanUserSubscriptionForm()

    if form.validate_on_submit():
        user = User.query.get(request.form.get('id'))

        if user: 
            subscription = Subscription()
            if subscription.cancel(user):
                flash('Subscription has been cancelled for user {0}'.format(user.name), 'success')
            else:
                flash('No subscription was cancelled', 'success')

    return redirect(url_for('admin.users'))


# Coupon --------------------------------------------------------------------

@admin.route('/coupons', methods=['GET', 'POST'])
@handle_stripe_exceptions
def coupons():
    """Fucntion to list all users in the database."""
    form_search = SearchForm()
    bulk_form = BulkDeleteForm()
    sort_by = Coupon.sort_by(request.args.get('sort', 'created_on'), 
                                            request.args.get('direction', 'desc'))
    order_values = '{0} {1}'.format(sort_by[0], sort_by[1])

    page = request.args.get('page', 1 , type=int)
    paginated_users = Coupon.query \
        .filter(Coupon.search(request.args.get('q', ''))) \
        .order_by(text(order_values)) \
        .paginate( page = page , per_page =current_app.config['FLASKY_POSTS_PER_PAGE'] , error_out = False )

    return render_template('admin/coupon/index.html', form=form_search,
                                coupons=paginated_users, bulk_form=bulk_form)

 
@admin.route('/coupons/new', methods=['GET', 'POST'])
@handle_stripe_exceptions
def coupons_new():
    coupon = Coupon()
    form = CouponForm(obj=coupon)

    if form.validate_on_submit():
        form.populate_obj(coupon)

        params = {
            'code': coupon.code,
            'duration': coupon.duration,
            'percent_off': coupon.percent_off,
            'amount_off': coupon.amount_off,
            'currency': coupon.currency,
            'redeem_by': coupon.redeem_by,
            'max_redemptions': coupon.max_redemptions,
            'duration_in_months': coupon.duration_in_months,
        }

        if Coupon.create(params):
            flash('Coupon has been created successfully.', 'success')
            return redirect(url_for('admin.coupon'))

    return render_template('admin/coupon/new.html', form=form, coupon=coupon)

@admin.route('/coupon/bulk_delete', methods=['POST'])
def coupon_bulk_delete():
    form = BulkDeleteForm()

    if form.validate_on_submit():
        ids = Coupon.get_bulk_action_ids(request.form.get('scope'),
                                        request.form.getlist('bulk_id'),
                                        query=request.args.get('q', ''))

        Coupon.bulk_delete(ids)

        flash('{0} coupon(s) will be deleted.'.format(len(ids)), 'succes')
    else:
        flash('No coupon were deleted, something went wrong', 'error')
    return redirect(url_for('admin.coupon'))

snakeeyes/blueprints/billing/__init__.py
from snakeeyes.blueprints.billing.views.billing import billing
from snakeeyes.blueprints.billing.views.stripe_webhook import stripe_webhook

snakeeyes/blueprints/billing/views/stripe_webhook.py
from flask import Blueprint, request
from stripe.error import InvalidRequestError

from lib.lib_json import render_json
from snakeeyes.extensions import Csrf
from snakeeyes.blueprints.billing.models.invoice import Invoice
from snakeeyes.blueprints.billing.gateways.stripecom import Event as PaymentEvent

stripe_webhook = Blueprint('stripe_webhook', __name__, url_prefix='/stripe_webhook')


@stripe_webhook.route('/event', methods=['POST'])
@Csrf.exempt
def event():
    if not request.json:
        return render_json(406, {'error': 'Mime-type is not application/json'})

    if request.json.get('id') is None:
        return render_json(406, {'error': 'Invalid Stripe event'})

    try:
        safe_event = PaymentEvent.retrieve(request.json.get('id'))
        parsed_event = Invoice.parse_from_event(safe_event)

        Invoice.prepare_and_save(parsed_event)
    except InvalidRequestError as e:
        # We could not parse the event.
        return render_json(422, {'error': str(e)})
    except Exception as e:
        # Return a 200 because something is really wrong and we want Stripe to
        # stop trying to fulfill this webhook request.
        return render_json(200, {'error': str(e)})

    return render_json(200, {'success': True})

snakeeyes/blueprints/contact/__init__.py
from flask import Blueprint

contact = Blueprint('contact', __name__, template_folder='templates')

from snakeeyes.blueprints.contact import views 

snakeeyes/blueprints/contact/views.py
from flask import render_template, url_for, flash, redirect, request



from snakeeyes.blueprints.contact.forms import ContactForm
from flask_login import current_user
from snakeeyes.blueprints.contact import contact
from snakeeyes.email import contact_me 


@contact.route('/contact', methods=['GET', 'POST'])
def index():
    form = ContactForm(obj=current_user)

    if form.validate_on_submit():
        email = form.email.data
        message = form.message.data
        data = {"email" : email, "message" : message}
        
        """import send_email here inorder to prevent circular import of celery app"""
        
        from snakeeyes.email import contact_me

        contact_me(email, message, 'contact', 'contact/mail/index' , data = data)
        flash("You will get a response soon", 'success')
        return redirect(url_for('contact.index'))

    return render_template('contact/index.html', form = form )

snakeeyes/blueprints/error_page/__init__.py
from flask import Blueprint

error = Blueprint('error', __name__)

from snakeeyes.blueprints.error_page import views

snakeeyes/blueprints/error_page/views.py
from snakeeyes.blueprints.error_page import error
from flask import render_template

@error.app_errorhandler(404)
def page_not_found(e):
    return render_template('error/error_404.html'), 404

@error.app_errorhandler(500)
def ser_error(e):
    return render_template('error/error_500.html'), 500
    

snakeeyes/templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block header %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{{ url_for('page.home') }}">
          <img src="{{ url_for('static', filename='images/snake-eyes.jpg') }}"
               class="img-responsive"
               width="229" height="50" title="Snake Eyes" alt="Snake Eyes"/>
        </a>
       
      </div>
      <ul class="nav navbar-nav">
        {% if current_user.role == 'admin' %}
            <li>
              {% include 'admin/_menu.html' %}
            </li>
          {% endif %}
          {% if current_user.is_authenticated and current_user.subscription %}
            <li><a href="{{ url_for('bet.place_bet') }}"> <span class="label label-primary">Place bet</span> </a></li>
          {% else %}
            <li><a href="{{ url_for('billing.pricing') }}">Pricing</a></li>
          {% endif %}
        </ul>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated and current_user.role == 'admin' %}
            <li class="dropdown">
              <a href="{{ url_for('user.settings') }}" class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button" aria-haspopup="true"
                 aria-expanded="false">Account
                <span class="caret"></span></a>
                <li><a href="{{url_for('user.logout')}}">logout</a></li>
                <li><a href="{{ url_for('admin.dashboard') }}">Admin</a></li>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('user.settings') }}">Settings</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session</li>
                <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
                <li><a href="{{ url_for('admin.dashboard') }}">Admin</a></li>
              </ul>
            </li>
          {% elif current_user.is_authenticated %}
            <li class="dropdown">
              <a href="{{ url_for('user.settings') }}" class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button" aria-haspopup="true"
                 aria-expanded="false">Account
                <span class="caret"></span></a>
                <li><a href="{{url_for('user.logout')}}">logout</a></li>
              <ul class="dropdown-menu">z
                <li><a href="{{ url_for('user.settings') }}">Settings</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session</li>
                <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
              </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}">Log in</a></li>
            <li><a href="{{ url_for('user.register') }}">Sign up</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}


{% block footer %}
  <li><a href="{{ url_for('contact.index') }}">Contact</a></li>
  <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
  <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
  <li><a href="{{ url_for('page.questions') }}">FAQ</a></li>

{% endblock %}

snakeeyes/templates/layouts/base.html
{% import 'billing/macros/billing.html' as billing with context %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
      
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">

      <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/eonasdan-bootstrap-datetimepicker.4.13.30.min.css') }}">
      
    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>

    <!-- Stripe JS API script -->
    <script src="https://js.stripe.com/v2/"></script>

    
    {% if config['ANALYTICS_GOOGLE_UA'] %}
    <!-- Google analytics script  -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', "{{ config['ANALYTICS_GOOGLE_UA'] }}", 'auto');
      ga('send', 'pageview');
    </script>
  {% endif %}
  </head>

  <body>
    

    {% block header %}{% endblock %}  

    {{ billing.card_expiring_warning() }}

    <main class="container">
      
      {# This macro function below will render flash messsages in the next request. #}

  
      {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
          <div id="flash-messages" class="row sm-margin-top">
            {% for category, message in messages  %}
              <div class="alert alert-{{category}}" role="alert">
                {{message}}
              </div>
            {% endfor %}
          </div>
        {% endif %}
      {% endwith %}


      <div class="md-margin-top">
        {% block heading %}{% endblock %}
      </div>
      
      {% block body %}{% endblock %}

    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">Snake Eyes &copy; 2016</li>
          {% block footer %} {% endblock %}    
        </ul>
      </div>
    </footer>

    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/main.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/vendor/eonasdan-bootstrap-datetimepicker.4.14.30.min.js') }}">
    </script>
  </body>
</html>

snakeeyes/templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block header %}
    <a href="{{url_for('page.home')}}">
        <img src="{{url_for('static', filename = 'images/snake-eyes.jpg' )}} " 
        class="img-responsive center-block md-margin-bottom"
         width="178" height="176" title="Snake Eyes" alt="Snake Eyes"/>
    </a>
{% endblock %}


{% block footer %}
    <li><a href="{{url_for('user.register')}}">Sign up today</a></li>
{% endblock %}